// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDINSGgkopxaNG5ZEiiOefSO4pSeyXlsJc',
    appId: '1:543133265298:android:a26c1a5c344a48cc3fa54b',
    messagingSenderId: '543133265298',
    projectId: 'medibot-2d210',
    storageBucket: 'medibot-2d210.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf5WXyN35o73o4K4pjf0woBCP0xb8myiM',
    appId: '1:543133265298:ios:d8fb656aa8dd3cc13fa54b',
    messagingSenderId: '543133265298',
    projectId: 'medibot-2d210',
    storageBucket: 'medibot-2d210.appspot.com',
    androidClientId: '543133265298-al8eu46jfct2fiklm7g08qbi81tkcrh8.apps.googleusercontent.com',
    iosClientId: '543133265298-50430clko8vg97f25e90rsvq6gep7jti.apps.googleusercontent.com',
    iosBundleId: 'com.ausam.medibot',
  );
}
